#!/bin/sh
# Code generated by vscodeenv freeze; This code is vscodeenv version lock script.
set -eu

# Visual Studio Code
vscodeenv install 1.54.1 --force

# Extensions
code --install-extension Unity.unity-debug@3.0.2 --force
code --install-extension VisualStudioExptTeam.vscodeintellicode@1.2.11 --force
code --install-extension bierner.markdown-mermaid@1.9.2 --force
code --install-extension eamodio.gitlens@11.2.1 --force
code --install-extension golang.go@0.22.1 --force
code --install-extension mads-hartmann.bash-ide-vscode@1.11.0 --force
code --install-extension ms-dotnettools.csharp@1.23.9 --force
code --install-extension ms-vscode-remote.remote-containers@0.163.0 --force
code --install-extension ms-vscode-remote.remote-ssh-edit@0.65.1 --force
code --install-extension ms-vscode-remote.remote-ssh@0.65.1 --force
code --install-extension ms-vscode-remote.remote-wsl@0.54.2 --force
code --install-extension ms-vscode-remote.vscode-remote-extensionpack@0.20.0 --force
code --install-extension ms-vsliveshare.vsliveshare@1.0.3784 --force
code --install-extension timonwong.shellcheck@0.13.2 --force
code --install-extension zxh404.vscode-proto3@0.5.3 --force
